# Generated by Django 4.1.5 on 2023-01-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, null=True, verbose_name="Subtotal"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="total",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, null=True, verbose_name="Total"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="total_gst_amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Total GST Amount",
            ),
        ),
    ]
