# Generated by Django 4.1.5 on 2023-01-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0002_alter_invoice_subtotal_alter_invoice_total_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoiceitem",
            name="cgst",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="CGST Rate"
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="cgst_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="CGST Amount",
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="igst",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="IGST Rate"
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="igst_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="IGST Amount",
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="sgst",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="SGST Rate"
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="sgst_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="SGST Amount",
            ),
        ),
    ]
